"""add_updated_at_to_requirement_reviews

Revision ID: bcdc56812745
Revises: f50f3e142f86
Create Date: 2026-03-31 10:03:54.871818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcdc56812745'
down_revision: Union[str, Sequence[str], None] = 'f50f3e142f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_reviews', 'updated_at')
    # ### end Alembic commands ###
