"""add unique constraint on project_id display_id

Revision ID: c28eb4bd1395
Revises: f1a971c0434d
Create Date: 2026-03-29 21:59:28.865215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28eb4bd1395'
down_revision: Union[str, Sequence[str], None] = 'f1a971c0434d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_requirements_project_display_id', 'requirements', ['project_id', 'display_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_requirements_project_display_id', 'requirements', type_='unique')
    # ### end Alembic commands ###
