"""add project_settings fk

Revision ID: ef0c54ab26e1
Revises: 87a2d3f47ca6
Create Date: 2026-03-28 15:52:39.565687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0c54ab26e1'
down_revision: Union[str, Sequence[str], None] = '87a2d3f47ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project_settings', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_settings', type_='foreignkey')
    # ### end Alembic commands ###
