"""add display_id and order_index to requirements

Revision ID: f1a971c0434d
Revises: ef0c54ab26e1
Create Date: 2026-03-29 21:39:16.651066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a971c0434d'
down_revision: Union[str, Sequence[str], None] = 'ef0c54ab26e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('display_id', sa.String(length=30), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('order_index', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'order_index')
    op.drop_column('requirements', 'display_id')
    # ### end Alembic commands ###
